[package]
name = "demsos"
version = "0.0.0"
edition = "2021"
description = "Desmos image uploader."
documentation = "https://docs.rs/demsos"
readme = "README.md"
repository = "https://github.com/7ap/demsos"
license = "MIT"

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
image = "0.24.4"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
